name: Criar um branch para uma nova issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Criar um branch
        uses: actions/create-branch@v2
        with:
          branch-name: /feature/${{ github.issue.title }}
          branch-base: main
          description: "Branch criado para resolver a issue #${{ github.issue.number }}"

