name: Criar um branch para uma nova issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: Criar um novo branch
        run: |
          git checkout -b feature/${{ github.event.issue.title }}
          touch task.md
          echo ${{ github.event.issue.title }} >> task.md
          git config user.email "github@gmail.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Generate task.md with description ${{ github.event.issue.title }} by GITHUB_ACTION"
          git push origin feature/${{ github.event.issue.title }}
