name: Criar um branch para uma nova issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: Criar um novo branch
        run: |
          git checkout -b feature
          git push origin feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
