name: Criar um branch para uma nova issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Criar um branch
        uses: actions/checkout@v2
      - name: Criar um branch personalizado
        run: |
          git checkout -b feature/${{ github.event.issue.title }} 
          git push origin feature/${{ github.event.issue.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
