name: Deploy em branches de release

on:
  push:
    branches: "release/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: Deploy na branch de release
        run: |
          git checkout -b realise-exists
          git push origin realise-exists
